version: '3'

services:
  aixp:
    build: ./aixp_contracts
    ports:
      - "8545:8545"
      - "8000:8000"
    volumes:
      - ./aixp_contracts:/app
    environment:
      - NODE_ENV=development
    command: ["./start.sh"]
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    networks:
      - aixp_net

networks:
  aixp_net:
    driver: bridge 